### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'load'. Error when running the example in the Readme

### ISSUE THREAD

**Issue by ORCelada** [neo4j-labs/rdflib-neo4j#1]
I have been testing the package, but at the first python script in the getting started I have run into this issue:

```
 g.load("https://raw.githubusercontent.com/jbarrasa/datasets/master/rdf/music.nt", format="nt")
AttributeError: 'Graph' object has no attribute 'load'

```

The only change I have done to the text is adding the credentials to my database, the rest is intact, so I don't know where the point of failure is.

The second option of the tutorial, using AuraDB, did work for me. I did notice that the equivalent line in the second option uses g.parse() instead of g.load(), so I tested changing it to parse, and the code ran. The nodes are added to my local database, but the second bit of printing the band names does not work. I am not sure if those are related issues. Either way, the g.load() line is causing problems.

**Comment by jbarrasa** [comment]
Hi @ORCelada , thanks for raising this. 
We've updated the code in the examples and hopefully now it should work as expected.
