### ISSUE TITLE
Understanding the scope of this project

### ISSUE THREAD

**Issue by reouvenzana** [neo4j-labs/rdflib-neo4j#26]
Hello,

I'm a beginner in Linked Data, graph databases, and Neo4j, so **please excuse me if I have any misconceptions**.

My goal is to build a knowledge graph, and while I'd like to benefit from the wide ecosystem and features offered by Neo4j, I'd also like to leverage the reasoning and inference capabilities of RDF data with RDFS and OWL (building new knowledge of already existing knowledge and logical rules, but I'm sure you know this better than me).

I've explored Neosemantics, but I find the "reasoning/inferencing" part limited and requiring complex syntax and special procedures, which I don't prefer. I was hoping for a more _native_ and _transparent_ approach, where I could declare that x is a subclass of y and automatically get x in my results when searching for y, without the need for additional complexity. One reason for that is that I plan to LLM to interact with the graph, but I'm concerned that crafting the necessary Cypher requests for each case using the current Neosemantics approach might be challenging for the LLM.

I'm trying to understand the scope of rdflib-neo4j and have the following questions:

1. Does rdflib-neo4j enable complete interaction with Neo4j using Python and RDF, potentially eliminating the need for Cypher?
2. Does rdflib-neo4j support the reasoning and inferencing capabilities offered by RDFS and OWL when submitting SPARQL queries?

I've reviewed the project's documentation but couldn't find clear answers to these questions. I would greatly appreciate any insights or clarifications you can provide.

Thank you

**Comment by alfredorubin96** [comment]
Hi @reouvenzana, thank you for posting this issue. Currently this project's scope is just data loading, however we are thinking of other features to add in the next iterations of this project. If you need anything and you think that it will be useful for the community feel free to create another issue. 

For now, you can just use Cypher to query the graph.
Let us know if you need anything else

**Comment by alfredorubin96** [comment]
I'll just close this issue, feel free to reopen it if you want to continue the discussion.
