### ISSUE TITLE
Adding SSO support to rdflib-neo4j library

### ISSUE THREAD

**Issue by sunilthunga** [neo4j-labs/rdflib-neo4j#30]
We are in the process of adding Neo4J in our Data Processing pipelines and started using reflib-neo4j library. As part of our organisation policies, our pipeline can only talk to Neo4J instances vis Single Sign On(SSO) using Non Personal Account(NPA). 

It seems SSO support is not added to the library and we were in touch with Nicolas Mervaillie and advised to report here. 

Could you please review this and help us to have the SSO functionality in rdflib-neo4j library.

Please let us know if you need any further details.

**Comment by alfredorubin96** [comment]
What we were thinking is to add the possibility to pass the driver, instead of configuring the driver inside the store. In this way we can have the maximum flexibility. Let us know if this solution is suitable for you

**Comment by sunilthunga** [comment]
Thank you for started looking into this. As long as we can able to authenticate via sso and also normal user/passwd, we are good.
